version: "3"
services:
  selenium:
    container_name: 'selenium'
    image: 'selenium/standalone-chrome:3.141'


  script_auto_register:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - selenium
